# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16_mc7MvymhkKcDAHzGGbXX_tol0qwbFO
"""

x = 10
print(x)

str = "workshop"
print(str)

x= 23
id(x)

print(type(x))

dir(object)

class student:
  def add():
    10+20

s = student();
res = s.add
print(res)

name = "dhineshKumar"
print(name)

